### ISSUE TITLE
今日识别数已尽

### ISSUE THREAD

**Issue by qgh1223** [QianJianTech/LaTeXLive#31]
识别遇到今日识别数已尽
这是啥？更新了？改了啥？

**Comment by qgh1223** [comment]
一个账号最大识别数是多少？

**Comment by smile-yan** [comment]
次数很少，好像十次就没了

**Comment by qgh1223** [comment]
> 次数很少，好像十次就没了
有啥别的免费的推荐吗

**Comment by smile-yan** [comment]
目前没有什么可以推荐的，找过破解版的 mathpix 安装包，但是没有用。

**Comment by Yuranruo** [comment]
> 一个账号最大识别数是多少？

点进个人中心，可见不买vip的情况下，每天只有两次识别次数

**Comment by olwician** [comment]
多创建几个账号（又不需要邮箱，也不需要手机）
