### ISSUE TITLE
请问你这个是否支持Upgreek扩展包？

### ISSUE THREAD

**Issue by Jesn** [QianJianTech/LaTeXLive#36]
例如： Upgreek扩展包里面的 欧姆  `\UPomega`，这种编辑器不支持

![image](https://user-images.githubusercontent.com/5728274/231937510-33d42f60-1134-42d4-8516-2a5a2379003f.png)

**Comment by JimmyChou1729** [comment]
可以支持 下个版本更新 @Jesn
