### ISSUE TITLE
手机号码格式错误  什么格式才可以

### ISSUE THREAD

**Issue by QHANT** [QianJianTech/LaTeXLive#6]
手机号码格式错误  什么格式才可以

**Comment by mommytalkltd** [comment]
可能您的手机号格式是新出的，原来的过滤器没能跟上时代。。有时间我再修复吧，不好意思

**Comment by KONEONE** [comment]
您好，我这边也同样出现了这个问题。似乎无法进行17***的号码注册。

**Comment by yuetao1011** [comment]
已经修复了最新的过滤器，此issues先关了
